### ISSUE TITLE
bug: Number of blog hits

### ISSUE THREAD

**Issue by wangyi12358** [CaliCastle/cali.so#3] opened 2023-05-27 14:11 UTC
Every time the /blog page is refreshed, the hit count of each blog will increase by one
<img width="1030" alt="image" src="https://github.com/CaliCastle/cali.so/assets/39055759/1e291526-e22b-4c9d-a2b7-d8b623b884a1">

**Comment by CaliCastle** [comment] 2023-05-27 14:29
Thank you for filing this bug, I've verified that it's valid, will be pushing up a fix soon!

**Comment by CaliCastle** [comment] 2023-05-27 15:24
Looks like it's caused by Next.js `<Link />`'s prefetch...

**Comment by CaliCastle** [comment] 2023-05-27 15:28
Fixed in https://github.com/CaliCastle/cali.so/commit/3ae4aa4c2788638feb880755c1a20b56eac75d98

**Closed** 2023-05-27 15:28 UTC
Labels: bug
